### ISSUE TITLE
12Factor: CloudWatchLogsへのログ転送

### ISSUE THREAD

**Issue by h-tsuboi918** [nacomer/nacomer_express#45]

**Comment by TomoyaHirano** [comment]
- 以下を参考にすると、コンテナの標準出力へ出せば、cloudwatchlogsへ転送されそう。
https://dev.classmethod.jp/articles/ecs-cloudwatch-logs/

- node-jsのloggerはlog4js-nodeが有名そう。
https://github.com/log4js-node/log4js-node
https://www.sejuku.net/blog/82816
- appendersでstdoutを指定すればよさそう。（環境ごとに出力先を変えられるように設定を作りたい）

**Comment by TomoyaHirano** [comment]
タスク定義: Nacomer-API:1 をみると、
以下の通り、CloudWatchLogsへの転送設定が入っていそうだけど、CloudWatchにはログがない。
![image](https://user-images.githubusercontent.com/71970550/100372222-49477680-304c-11eb-8e74-46c1620a79b4.png)
![image](https://user-images.githubusercontent.com/71970550/100372291-5f553700-304c-11eb-8f6b-8a88b532dad8.png)

**Comment by TomoyaHirano** [comment]
以下の設定で、ECS（標準出力）→CloudWatchへログ転送できていそう。
GithubActionsで指定する？、ECSのタスク定義的に問題がないか、坪井さんに確認したい。

![image](https://user-images.githubusercontent.com/71970550/100373962-ec00f480-304e-11eb-8556-9f906e008f53.png)

![image](https://user-images.githubusercontent.com/71970550/100373981-f4592f80-304e-11eb-96ac-1820b0166c6b.png)

![image](https://user-images.githubusercontent.com/71970550/100374016-02a74b80-304f-11eb-8989-e20b75ffb120.png)
